name: Bitbucket to GitHub Migration

on:
  workflow_dispatch:

jobs:
  migrate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout this repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git gh
        pip install requests

    - name: Authenticate GH CLI (required to create repos)
      run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

    - name: Run Migration Script
      run: python migration_script.py
''''''   
    - name: Upload logs and reports
        uses: actions/upload-artifact@v4
        with:
          name: migration-logs
          path: |
            github_migration.log
            migration_report.csv
            logs_report.zip
''''''