name: Bitbucket to GitHub Migration

on:
  workflow_dispatch:

jobs:
  migrate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git zip curl
          pip install requests

      - name: Run Migration Script
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_PAT }}
          BITBUCKET_PAT: ${{ secrets.BITBUCKET_PAT }}
        run: python migration_script.py

      - name: Upload Logs and Reports
        uses: actions/upload-artifact@v4
        with:
          name: migration-logs
          path: |
            github_migration.log
            migration_report.csv
