name: Bitbucket to GitHub Migration

on:
  workflow_dispatch:  # manual trigger from GitHub UI

jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install git and zip tools
        run: sudo apt-get update && sudo apt-get install -y git zip curl

      - name: Install Python dependencies (if any)
        run: pip install requests

      - name: Run migration script
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_PAT }}
          BITBUCKET_PAT: ${{ secrets.BITBUCKET_PAT }}
          GITHUB_ORGANISATION: ${{ secrets.GITHUB_ORGANISATION }}
          BITBUCKET_KEY: ${{ secrets.BITBUCKET_KEY }}
          ENTERPRISE_GIT_URL: ${{ secrets.ENTERPRISE_GIT_URL }}
          ENTERPRISE_BITBUCKET_URL: ${{ secrets.ENTERPRISE_BITBUCKET_URL }}
        run: |
          python migration_script.py

      - name: Upload logs and reports
        uses: actions/upload-artifact@v4
        with:
          name: migration-logs
          path: |
            github_migration.log
            migration_report.csv
            logs_report.zip